version: '3.8'
services:
  rocket-django:
    env_file:
      - ".env"
    container_name: rocket_django
    restart: always
    build: .
    networks:
      - db_network
      - web_network

  # postgres:
  #   environment:
  #     POSTGRES_USER: "${POSTGRES_USER}"
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #     POSTGRES_DB: "${POSTGRES_DB}"
  #   image: "postgres:16.0-bookworm"
  #   restart: always
  #   networks:
  #     - db_network
  #   stop_grace_period: "3s"
  #   volumes:
  #     - "postgres:/var/lib/postgresql/data"   
  #   env_file:
  #     - ".env"
  
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - rocket-django
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres: {}