# Generated by Django 4.2.6 on 2023-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hex_kolor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kwiat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kategorie_i_kolory', models.CharField(default='', max_length=50000)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_utworzenia', models.DateTimeField(auto_now=True)),
                ('wartosc', models.CharField(default='', max_length=500000)),
            ],
        ),
    ]
