# Generated by Django 4.2.6 on 2023-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_kolory_kwiat_raport'),
    ]

    operations = [
        migrations.AddField(
            model_name='kolory',
            name='custom_background',
            field=models.ImageField(blank=True, null=True, upload_to='tla'),
        ),
    ]
