# Generated by Django 4.2.6 on 2023-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_kolory_custom_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwiat',
            name='kolejnosc',
            field=models.IntegerField(null=True),
        ),
    ]
