# Generated by Django 4.2.6 on 2023-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_zamowienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwiat',
            name='kategorie_i_kolory',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='raport',
            name='wartosc',
            field=models.JSONField(),
        ),
    ]
